const ASSET_VERSION = "complexity-v2";
const versioned = (path) => `${path}?v=${ASSET_VERSION}`;

export const ASSETS = {
  keyArt: versioned("assets/generated/emberwild-key-art.png"),
  shrineArt: versioned("assets/generated/emberwild-shrine-hd.png"),
  wardArt: versioned("assets/generated/emberwild-ward-hd.png"),
  bossArt: versioned("assets/generated/ashwarden-boss-hd.png"),
  tiles: versioned("assets/environment/tiles-imagen-hd.png"),
  objects: versioned("assets/environment/objects.png"),
  player: versioned("assets/characters/player.png"),
  thornling: versioned("assets/characters/thornling.png"),
  wisp: versioned("assets/characters/wisp.png"),
  ashwarden: versioned("assets/characters/ashwarden.png"),
  slash: versioned("assets/fx/slash.png"),
  icons: versioned("assets/ui/icons.png"),
  bgmExplore: versioned("assets/audio/bgm/moonlit-castle-ruins.mp3"),
  bgmBoss: versioned("assets/audio/bgm/ashwarden-boss.mp3"),
  sfxSlash: versioned("assets/audio/sfx/slash.mp3"),
  sfxDash: versioned("assets/audio/sfx/dash.wav"),
  sfxPickup: versioned("assets/audio/sfx/pickup-gem.wav"),
  sfxGate: versioned("assets/audio/sfx/gate-open.ogg"),
  sfxBeacon: versioned("assets/audio/sfx/beacon.wav"),
  sfxEnemyHurt: versioned("assets/audio/sfx/enemy-hurt.wav"),
  sfxPlayerHit: versioned("assets/audio/sfx/player-hit.wav"),
  sfxHeal: versioned("assets/audio/sfx/heal.wav"),
  sfxConfirm: versioned("assets/audio/sfx/ui-confirm.wav"),
  sfxBossDie: versioned("assets/audio/sfx/boss-die.wav"),
};

export const TILE = 32;

export const TILE_INDEX = {
  grass: 0,
  grassFlowers: 1,
  stone: 2,
  moss: 3,
  water: 4,
  bridge: 5,
  dirt: 6,
  pit: 7,
  wall: 8,
  tree: 9,
  bramble: 10,
  gateClosed: 11,
  gateOpen: 12,
  pillar: 13,
  emberVine: 14,
  stairs: 15,
  flowers: 16,
  roots: 17,
  crackedStone: 18,
  altar: 19,
  dark: 20,
  ruinCap: 21,
  fireVine: 22,
  stepStone: 23,
  fern: 24,
  glowMoss: 25,
  log: 26,
  runeFloor: 27,
  leafPile: 28,
  mistStone: 29,
  emberRock: 30,
  thornGrass: 31,
};

export const OBJECT_FRAME = {
  shard: 0,
  heart: 1,
  key: 2,
  chestClosed: 3,
  chestOpen: 4,
  beacon: 5,
  potion: 6,
  relic: 7,
  sigil: 8,
  obelisk: 9,
  loreStone: 10,
  emberWell: 11,
};
